/**
 * Risk scoring and report export.
 */

import type { AgentReport, Severity } from "@/types";
import { SEVERITY_META } from "@/lib/severity";

// Per-finding contribution to the aggregate risk score (0–100, higher = worse).
const SEVERITY_WEIGHT: Record<Severity, number> = {
  critical: 40,
  high: 20,
  medium: 8,
  low: 2,
  info: 0,
};

/** Aggregate risk score in [0, 100]. Higher means more risk. */
export function computeRiskScore(report: AgentReport): number {
  const total = report.prioritizedFindings.reduce(
    (sum, f) => sum + (SEVERITY_WEIGHT[f.severity] ?? 0),
    0,
  );
  return Math.min(100, total);
}

/** Map a numeric score to a severity-like band (reuses severity colors). */
export function riskBand(score: number): { label: string; severity: Severity } {
  if (score >= 75) return { label: "Critical Risk", severity: "critical" };
  if (score >= 50) return { label: "High Risk", severity: "high" };
  if (score >= 25) return { label: "Moderate Risk", severity: "medium" };
  if (score > 0) return { label: "Low Risk", severity: "low" };
  return { label: "No Known Risk", severity: "info" };
}

export function severityColor(severity: Severity): string {
  return SEVERITY_META[severity].text;
}

// ── Markdown export ──────────────────────────────────────────────

/** Build a shareable Markdown security report from the AI review. */
export function buildMarkdownReport(report: AgentReport): string {
  const score = computeRiskScore(report);
  const band = riskBand(score);
  const lines: string[] = [];

  lines.push(`# Sentinel AI — Security Review`);
  lines.push("");
  lines.push(`- **Repository:** \`${report.repositoryId}\``);
  lines.push(`- **Overall risk:** ${report.overallRisk.toUpperCase()} (${band.label}, score ${score}/100)`);
  lines.push(`- **Findings analyzed:** ${report.totalInputFindings} raw → ${report.prioritizedFindings.length} prioritized (${report.duplicatesRemoved} duplicates removed)`);
  if (report.modelUsed) lines.push(`- **Model:** ${report.modelUsed}`);
  lines.push("");

  lines.push(`## Executive Summary`);
  lines.push("");
  lines.push(report.executiveSummary);
  lines.push("");

  lines.push(`## Developer Summary`);
  lines.push("");
  lines.push(report.developerSummary);
  lines.push("");

  if (report.prioritizedFindings.length) {
    lines.push(`## Prioritized Findings`);
    lines.push("");
    for (const f of report.prioritizedFindings) {
      lines.push(`### ${f.priority}. ${f.title} — ${f.severity.toUpperCase()}`);
      lines.push("");
      lines.push(`- **Category:** ${f.category}`);
      if (f.affectedFiles.length) lines.push(`- **Files:** ${f.affectedFiles.join(", ")}`);
      lines.push(`- **Detected by:** ${f.scanners.join(", ") || "n/a"}`);
      lines.push(`- **Confidence:** ${f.confidence}`);
      lines.push(`- **Why it matters:** ${f.whyItMatters}`);
      if (f.exploitability) lines.push(`- **Exploitability:** ${f.exploitability}`);
      lines.push(`- **Remediation:** ${f.remediation}`);
      lines.push("");
    }
  }

  if (report.correlations.length) {
    lines.push(`## Correlations`);
    lines.push("");
    for (const c of report.correlations) lines.push(`- ${c}`);
    lines.push("");
  }

  if (report.notes) {
    lines.push(`## Notes`);
    lines.push("");
    lines.push(report.notes);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by Sentinel AI._`);
  return lines.join("\n");
}

/** Trigger a client-side download of the Markdown report. */
export function downloadReport(report: AgentReport): void {
  const blob = new Blob([buildMarkdownReport(report)], {
    type: "text/markdown;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `sentinel-report-${report.repositoryId.slice(0, 8)}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
